/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PAT;

import backend.GameMethods;
import backend.GameStateManager;
import backend.UserManager;

/**
 *
 * @author user-pc
 */
public class EndingScreen extends javax.swing.JFrame {

    private GameMethods gameMethods;
    private UserManager userManager;

    /**
     * Creates new form EndingScreen
     */
    public EndingScreen() {
        initComponents();
        //centers and initilizes methods
        setLocationRelativeTo(null);
        gameMethods = GameStateManager.getGameMethods();
        userManager = GameStateManager.getUserManager();
        //methods to set images and text
        gameMethods.End(win_loss);
        gameMethods.getEndPicture(userManager.getUserPicNumber(), nameplace, picplace);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nameplace = new javax.swing.JLabel();
        picplace = new javax.swing.JLabel();
        win_loss = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rigtarrow.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        nameplace.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        nameplace.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nameplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, -1, -1));
        getContentPane().add(picplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 410, 190, 290));
        picplace.getAccessibleContext().setAccessibleDescription("");

        win_loss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/endLoss.png"))); // NOI18N
        win_loss.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                win_lossPropertyChange(evt);
            }
        });
        getContentPane().add(win_loss, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void win_lossPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_win_lossPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_win_lossPropertyChange

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //bring back to main screen and restart
        GameStateManager.Recycle();
        LandingScreen land = new LandingScreen();
        land.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameplace;
    private javax.swing.JLabel picplace;
    private javax.swing.JLabel win_loss;
    // End of variables declaration//GEN-END:variables
}
